### ISSUE TITLE
backend: local ?

### ISSUE THREAD

**Issue by saveyour** [jpillora/node-torrent-cloud#2]
first, cool project. 

second, i dont know node otherwise i'd be doing this myself (tried to, actually) but is there a way to just have local storage without a backend? i used the _template.js example to create a local.js that just does nada but for some reason it hangs after i try to load a torrent

not sure if thats a bug in something else, as even without my changes i couldn't get torrent-cloud to load a torrent and download successfully using the mega backend..

i  guess it could be a port-forwarding issue as i'm using it inside of a lxc container on an ubuntu 14.04 vps

(a local or ftp backend would be tits)

**Comment by jpillora** [comment]
Thanks, it's on the [todo](https://github.com/jpillora/node-torrent-cloud#todo), just need to find time. As mentioned though in the README, I want to rewrite this is Go for portability and deployability so if I do get time (big work project atm) I'll most likely spend it on the Go version. Should be easier second time around, especially since I'll reuse the frontend.

``` js
exports.upload = function(torrentFile, callback) {
  var file = fs.createWriteStream("/my/path/" + torrentFile.path);
  var download = torrent.createStream();
  download.pipe(file);
  download.once('error', callback);
  download.once('close', callback);
};
```

Something like that should work. Currently, I'm using utorrent server for linux for locally stored torrents. Mainly wrote this for so I could download files directly to S3.

**Comment by jpillora** [comment]
Closing this, version 2 writes downloads to disk
